<?php

namespace Tests\Feature\MasterData;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CitiesTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutMiddleware(VerifyCsrfToken::class);
        \Auth::attempt(['username' => 'admin' , 'password' => '123456']);
    }

    public function testCityRouteExist()
    {
        $response = $this->get('/master-data/cities');

        $response->assertStatus(200);

    }
}
