<?php
return [
    'dashboardIcon'         =>  'fas fa-chart-pie sidebar-icon',
    'masterDataIcon'        =>  'fas fa-folder-open sidebar-icon',
    'securityIcon'          =>  'fas fa-cctv sidebar-icon',
    'qualityControlIcon'    =>  'fas fa-flask sidebar-icon',
    'productionIcon'        =>  'fad fa-conveyor-belt sidebar-icon',
    'usersIcon'             =>  'far fa-users',
    'rolesIcon'             =>  'far fa-user-tag',
    'governoratesIcon'      =>  'fas fa-map-marked-alt',
    'citiesIcon'            =>  'fas fa-directions',
    'centersIcon'           =>  'fas fa-map-marker-alt',
    'itemGroupsIcon'        =>  'far fa-apple-crate',
    'itemTypesIcon'         =>  'fas fa-tags',
    'itemsIcon'             =>  'fad fa-apple-alt',
    'suppliersIcon'         =>  'fas fa-user-tie',
    'scalesIcon'            =>  'fas fa-balance-scale-right',
    'qcElementsIcon'        =>  'fal fa-vial',
    'qcTestIcon'            =>  'far fa-clipboard-list-check',
    'truckArrivalIcon'      =>  'fas fa-shipping-timed',
    'blockedDriversIcon'    =>  'fas fa-do-not-enter',
    'arrivedTrucksIcon'     =>  'fal fa-truck-container',
    'sampledTestIcon'       =>  'fas fa-tasks',
    'EditTruckQueueIcon'    =>  'far fa-history',
    'rawProcessIcon'        =>  'fas fa-conveyor-belt-alt',
    'scrapProcessIcon'      =>  'far fa-recycle',
    'scaleIcon'             =>  'fal fa-barcode-read',
    'truckSummaryIcon'      >   'far fa-recycle',
];
